---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${APP_NAME}-secrets
  namespace: ${AKS_NAMESPACE}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "${AZURE_KEYVAULT_CLIENT_ID}"
    keyvaultName: "${AZURE_KEYVAULT_NAME}"
    tenantId: "${AZURE_TENANT_ID}"
    objects: |
      array:
        - |
          objectName: fastapi-admin-db-host
          objectType: secret
        - |
          objectName: fastapi-admin-db-port
          objectType: secret
        - |
          objectName: fastapi-admin-db-user
          objectType: secret
        - |
          objectName: fastapi-admin-db-password
          objectType: secret
        - |
          objectName: fastapi-admin-db-name
          objectType: secret
        - |
          objectName: fastapi-admin-jwt-secret-key
          objectType: secret
  secretObjects:
    - secretName: fastapi-admin-db-secret
      type: Opaque
      data:
        - objectName: fastapi-admin-db-host
          key: shost
        - objectName: fastapi-admin-db-port
          key: sport
        - objectName: fastapi-admin-db-user
          key: suser
        - objectName: fastapi-admin-db-password
          key: spassword
        - objectName: fastapi-admin-db-name
          key: sdatabase
        - objectName: fastapi-admin-jwt-secret-key
          key: SECRET_KEY
