---
apiVersion: v1
kind: Namespace
metadata:
  name: ${GKE_NAMESPACE}
  labels:
    app.kubernetes.io/name: fastapi-user-app
    environment: production
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${GKE_SA}
  namespace: ${GKE_NAMESPACE}
  annotations:
    iam.gke.io/gcp-service-account: ${GKE_GSA_EMAIL}
