formatter: markdown table

sections:
  show:
    - header
    - requirements
    - providers
    - modules
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
